package mappingdefinition

import (
	"context"
	"fmt"
	"testing"

	"github.com/Ramsey-B/stem/pkg/database"
	"github.com/Ramsey-B/lotus/pkg/fields"
	"github.com/Ramsey-B/lotus/pkg/links"
	"github.com/Ramsey-B/lotus/pkg/mapping"
	"github.com/Ramsey-B/lotus/pkg/steps"
)

func TestMappingDefinitionRepository_Upsert(t *testing.T) {
	t.Skip("skipping for now")
	repo := Repository{}

	repo.Upsert(context.Background(), mapping.MappingDefinition{
		MappingDefinitionFields: mapping.MappingDefinitionFields{
			ID:       "1",
			TenantID: "1",
			UserID:   "1",
			Version:  1,
		},
		SourceFields: fields.Fields{},
		TargetFields: fields.Fields{},
		Steps:        map[string]*steps.Step{},
		Links:        links.Links{},
	})

	// Suppose we defined following type for user db.
	type User struct {
		ID     int64  `db:"id" fieldtag:"pk"`
		Name   string `db:"name"`
		Status int    `db:"status"`
	}

	// Parse user struct. The userStruct can be a global variable.
	// It's guraanteed to be thread-safe.
	var userStruct = database.NewStruct(new(User))

	// Prepare INSERT query.
	// Suppose that user id is generated by database.
	user := &User{
		Name:   "Huan Du",
		Status: 1,
	}
	ib := userStruct.WithoutTag("pk").InsertInto("user", user)

	// Execute the query.
	sql, args := ib.Build()

	fmt.Println(sql, args)
}
